sass:
  style: :compressed  # Change to :expanded for debugging

permalink: /:year/:month/:day/:title.html

url: http://tiepvupsu.github.io
future: true
debug: false

# Build settings
markdown: kramdown
permalink: pretty
future: true
highlighter: rouge
linenos: true
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Disqus post comments
disqus_shortname: tiepvu

paginate: 5
paginate_path: "/page:num/"

# `gems: [jekyll-paginate]`

gems:
  - jekyll-sitemap
  - jekyll-paginate