# Site settings
title: Blog của Tiệp Vũ
email: vuhuutiep@gmail.com
# description: "Fundatmentals of Machine Learning and Optimization Algorithms"
baseurl: ""
url: "http://tiepvupsu.github.io"
# twitter_username: karpathy
github_username:  tiepvupsu

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
