# Site settings
title: Andrej Karpathy blog
email: 
description: "Andrej Karpathy Blog. Musings of a Computer Scientist."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: karpathy
github_username:  karpathy

# Build settings
markdown: redcarpet
permalink: pretty
