sass:
  style: :compressed  # Change to :expanded for debugging

permalink: /:year/:month/:day/:title.html

url: http://tiepvupsu.github.io
future: true
debug: false

# Build settings
markdown: kramdown
permalink: pretty
future: true
highlighter: pygments
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: pyments

# Disqus post comments
disqus_shortname: tiepvu


gems:
  - jekyll-sitemap