# Site settings
title: Machine Learning cơ bản
email: vuhuutiep@gmail.com
# description: "Fundatmentals of Machine Learning and Optimization Algorithms"
baseurl: ""
url: "http://tiepvupsu.github.io"
# twitter_username: karpathy
github_username:  tiepvupsu

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
# markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]