# Site settings
title: Machine Learning cơ bản
email: vuhuutiep@gmail.com
# description: "Fundatmentals of Machine Learning and Optimization Algorithms"
baseurl: ""
url: "http://tiepvupsu.github.io"
# twitter_username: karpathy
github_username:  tiepvupsu

# Build settings
markdown: kramdown
permalink: pretty
future: true
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
# markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
# octopress-page-view
page-view:
  service_account_email:    # XXXXXX@developer.gserviceaccount.com
  key_file: privatekey.p12  # service account private key file
  key_secret: notasecret    # service account private key's password
  profileID:                # ga:XXXXXXXX
  start: 3 years ago        # Beginning of report
  end: now                  # End of report
  metric: ga:pageviews      # Metric code
  segment: gaid::-1         # All visits
  filters:                  # optional